import { PrismaClient, Role, Unit, DriverEmploymentStatus, DriverShiftStatus, DriverLicenseClass } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const DRIVER_SEEDS = [
  {
    code: 'TA-NV-1082',
    username: 'driver.hung.nv',
    fullName: 'Nguyễn Văn Hùng',
    phone: '0988 123 456',
    unit: Unit.NT1,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_FC,
    licenseNumber: '790182736412',
    licenseExpiryDate: new Date('2028-05-12'),
    healthCheckExpiryDate: new Date('2027-03-20'),
    currentLocation: 'Lô A03 - Nông trường 1 (Đang cày lật đất)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300',
    joinedDate: new Date('2021-03-10'),
    notes: 'Lái xe đầu kéo & máy cày lành nghề, đạt danh hiệu Lái xe xuất sắc năm 2025',
    enterprise: 'Nông trường 1',
    team: 'Đội Vận tải Cơ giới 01',
    position: 'Lái xe đầu kéo',
    idCardNumber: '079085001234',
    idCardIssueDate: '2021-05-10',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'hung.nv@thacoagri.vn',
  },
  {
    code: 'TA-NV-2091',
    username: 'driver.sokha',
    fullName: 'Sokha Chamnan',
    phone: '+855 88 765 4321',
    unit: Unit.NT2,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.BANG_MAY_NONG_NGHIEP,
    licenseNumber: 'CAM-8829104',
    licenseExpiryDate: new Date('2027-10-18'),
    healthCheckExpiryDate: new Date('2027-01-15'),
    currentLocation: 'Khoảnh 2 - Nông trường 2 (Đang bừa đất tơi)',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
    joinedDate: new Date('2022-07-15'),
    notes: 'Tài xế bản địa thông thạo máy kéo Kubota, tiết kiệm nhiên liệu định mức',
    enterprise: 'Nông trường 2',
    team: 'Đội Cơ giới Làm đất 02',
    position: 'Thợ vận hành máy kéo',
    idCardNumber: 'KHM-09928172',
    idCardIssueDate: '2020-04-12',
    idCardIssuePlace: 'Kratie Provincial Police',
    email: 'sokha.chamnan@thacoagri.vn',
  },
  {
    code: 'TA-NV-1104',
    username: 'driver.duc.tm',
    fullName: 'Trần Minh Đức',
    phone: '0977 456 789',
    unit: Unit.XN_BO,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.SAN_SANG,
    licenseClass: DriverLicenseClass.HANG_C,
    licenseNumber: '790192837465',
    licenseExpiryDate: new Date('2026-09-15'), // Sắp hết hạn < 30 ngày (Alert)
    healthCheckExpiryDate: new Date('2026-10-10'),
    currentLocation: 'Bãi Xe Xí Nghiệp Bò (Sẵn sàng nhận phân công)',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300',
    joinedDate: new Date('2023-08-19'),
    notes: 'Chuyên tuyến vận chuyển phụ phẩm chuối & phối trộn thức ăn TMR',
    enterprise: 'Xí nghiệp Bò',
    team: 'Đội Vận chuyển thức ăn TMR',
    position: 'Lái xe tải ben 10T',
    idCardNumber: '079091002345',
    idCardIssueDate: '2022-03-15',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'duc.tm@thacoagri.vn',
  },
  {
    code: 'TA-NV-3120',
    username: 'driver.nam.lh',
    fullName: 'Lê Hoàng Nam',
    phone: '0912 334 999',
    unit: Unit.BAN_CO_GIOI,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_FC,
    licenseNumber: '790203948576',
    licenseExpiryDate: new Date('2028-11-25'),
    healthCheckExpiryDate: new Date('2026-09-01'), // Quá hạn khám SK (Alert)
    currentLocation: 'Quốc Lộ 4 ➔ Cảng Quốc Tế Sihanoukville',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300',
    joinedDate: new Date('2020-02-01'),
    notes: 'Tài xế Container đường dài xuất khẩu, luôn chạy đúng tốc độ định mức',
    enterprise: 'Ban Cơ giới',
    team: 'Đội Xe Container Đường dài',
    position: 'Lái xe đầu kéo Container',
    idCardNumber: '079088003456',
    idCardIssueDate: '2019-11-20',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'nam.lh@thacoagri.vn',
  },
  {
    code: 'TA-NV-1045',
    username: 'driver.rathana',
    fullName: 'Keo Rathana',
    phone: '+855 97 123 4567',
    unit: Unit.NT1,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.BANG_MAY_NONG_NGHIEP,
    licenseNumber: 'CAM-7718293',
    licenseExpiryDate: new Date('2027-04-30'),
    healthCheckExpiryDate: new Date('2027-02-14'),
    currentLocation: 'Lô B04 - Nông trường 1 (Đang kéo cáp chuối)',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300',
    joinedDate: new Date('2022-10-01'),
    notes: 'Vận hành cáp kéo chuối và mooc gom nông sản tại các lô thu hoạch',
    enterprise: 'Nông trường 1',
    team: 'Đội Cơ giới Nông trường 1',
    position: 'Thợ vận hành máy kéo',
    idCardNumber: 'KHM-08819283',
    idCardIssueDate: '2021-08-10',
    idCardIssuePlace: 'Kratie Provincial Police',
    email: 'rathana.keo@thacoagri.vn',
  },
  {
    code: 'TA-NV-2201',
    username: 'driver.tuan.pv',
    fullName: 'Phạm Văn Tuấn',
    phone: '0933 556 677',
    unit: Unit.TT_BTSC,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.SAN_SANG,
    licenseClass: DriverLicenseClass.HANG_C,
    licenseNumber: '790214859607',
    licenseExpiryDate: new Date('2029-01-12'),
    healthCheckExpiryDate: new Date('2026-11-25'),
    currentLocation: 'Xưởng BTSC Trung tâm (Sẵn sàng điều động)',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300',
    joinedDate: new Date('2021-06-20'),
    notes: 'Kiêm kỹ thuật viên sửa chữa cơ giới, lái xe cẩu tự hành cứu hộ',
    enterprise: 'Trung tâm BTSC',
    team: 'Đội Cứu hộ Kỹ thuật',
    position: 'Lái xe cứu hộ kiêm Thợ máy',
    idCardNumber: '079089004567',
    idCardIssueDate: '2020-07-15',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'tuan.pv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1334',
    username: 'driver.vong',
    fullName: 'Heng Vong',
    phone: '+855 88 990 0112',
    unit: Unit.NT2,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.SAN_SANG,
    licenseClass: DriverLicenseClass.HANG_B2,
    licenseNumber: 'CAM-9920194',
    licenseExpiryDate: new Date('2030-05-20'),
    healthCheckExpiryDate: new Date('2027-06-10'),
    currentLocation: 'Trạm cơ vụ Nông trường 2',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300',
    joinedDate: new Date('2023-02-14'),
    notes: 'Lái xe bán tải đưa đón cán bộ kỹ thuật và tuần tra an ninh nông trường',
    enterprise: 'Nông trường 2',
    team: 'Tổ Cơ vụ Nông trường 2',
    position: 'Lái xe công vụ',
    idCardNumber: 'KHM-07718294',
    idCardIssueDate: '2022-01-15',
    idCardIssuePlace: 'Kratie Provincial Police',
    email: 'vong.heng@thacoagri.vn',
  },
  {
    code: 'TA-NV-3412',
    username: 'driver.long.vt',
    fullName: 'Võ Thành Long',
    phone: '0977 889 911',
    unit: Unit.BAN_CO_GIOI,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_FC,
    licenseNumber: '790225960718',
    licenseExpiryDate: new Date('2028-08-30'),
    healthCheckExpiryDate: new Date('2026-12-15'),
    currentLocation: 'DP2 ➔ DP Tổng kho (Đang kéo container chuối)',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300',
    joinedDate: new Date('2021-04-10'),
    notes: 'Chuyên gia vận hành mooc sàn & mooc thùng chở chuối xuất khẩu',
    enterprise: 'Ban Cơ giới',
    team: 'Đội Xe Container Đường dài',
    position: 'Lái xe đầu kéo Container',
    idCardNumber: '079087005678',
    idCardIssueDate: '2019-08-20',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'long.vt@thacoagri.vn',
  },
  {
    code: 'TA-NV-1099',
    username: 'driver.thang.nh',
    fullName: 'Nguyễn Hữu Thắng',
    phone: '0966 334 455',
    unit: Unit.NT1,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.SAN_SANG,
    licenseClass: DriverLicenseClass.HANG_C,
    licenseNumber: '790236071829',
    licenseExpiryDate: new Date('2028-03-25'),
    healthCheckExpiryDate: new Date('2026-09-25'), // Sắp hết hạn < 30 ngày (Alert)
    currentLocation: 'Bãi Xe NT1 (Chờ lệnh vận chuyển)',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300',
    joinedDate: new Date('2022-11-05'),
    notes: 'Lái xe tải thùng giao vật tư phân bón & túi bao buồng chuối',
    enterprise: 'Nông trường 1',
    team: 'Đội Vận tải Nội bộ',
    position: 'Lái xe tải vận chuyển vật tư',
    idCardNumber: '079090006789',
    idCardIssueDate: '2021-02-18',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'thang.nh@thacoagri.vn',
  },
  {
    code: 'TA-NV-2115',
    username: 'driver.samnang',
    fullName: 'Chea Samnang',
    phone: '+855 88 334 4556',
    unit: Unit.NT2,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.BANG_MAY_NONG_NGHIEP,
    licenseNumber: 'CAM-8839201',
    licenseExpiryDate: new Date('2027-08-14'),
    healthCheckExpiryDate: new Date('2027-04-10'),
    currentLocation: 'Lô D02 - Nông trường 2 (Đang xới rãnh bón lót)',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300',
    joinedDate: new Date('2023-05-12'),
    notes: 'Kinh nghiệm cày xới rãnh và lên luống chuẩn kỹ thuật nông học',
    enterprise: 'Nông trường 2',
    team: 'Đội Cơ giới Làm đất 02',
    position: 'Thợ vận hành máy nông nghiệp',
    idCardNumber: 'KHM-06619284',
    idCardIssueDate: '2022-09-10',
    idCardIssuePlace: 'Kratie Provincial Police',
    email: 'samnang.chea@thacoagri.vn',
  },
  {
    code: 'TA-NV-1002',
    username: 'driver.toan.dv',
    fullName: 'Đinh Văn Toàn',
    phone: '0981 223 344',
    unit: Unit.NT1,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.SAN_SANG,
    licenseClass: DriverLicenseClass.HANG_C,
    licenseNumber: '790247182930',
    licenseExpiryDate: new Date('2028-12-05'),
    healthCheckExpiryDate: new Date('2027-01-20'),
    currentLocation: 'Bãi đỗ trung tâm NT1',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300',
    joinedDate: new Date('2022-04-15'),
    notes: 'Lái xe tải chở chuối tươi từ trạm đóng gói ra kho mát',
    enterprise: 'Nông trường 1',
    team: 'Đội Vận tải Nội bộ',
    position: 'Lái xe tải nhẹ',
    idCardNumber: '079086007890',
    idCardIssueDate: '2020-10-12',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'toan.dv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1003',
    username: 'driver.cuong.bv',
    fullName: 'Bùi Văn Cường',
    phone: '0908 776 655',
    unit: Unit.NT1,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_FC,
    licenseNumber: '790258293041',
    licenseExpiryDate: new Date('2027-07-20'),
    healthCheckExpiryDate: new Date('2026-11-10'),
    currentLocation: 'Tuyến đường NT1 ➔ Cảng xuất khẩu',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
    joinedDate: new Date('2021-09-01'),
    notes: 'Lái xe đầu kéo Container lạnh chất lượng cao, không có lỗi vi phạm',
    enterprise: 'Nông trường 1',
    team: 'Đội Xe Container',
    position: 'Lái xe đầu kéo',
    idCardNumber: '079084008901',
    idCardIssueDate: '2019-05-18',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'cuong.bv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1004',
    username: 'driver.huy.lq',
    fullName: 'Lê Quang Huy',
    phone: '0918 445 566',
    unit: Unit.NT2,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.SAN_SANG,
    licenseClass: DriverLicenseClass.HANG_B2,
    licenseNumber: '790269304152',
    licenseExpiryDate: new Date('2029-06-15'),
    healthCheckExpiryDate: new Date('2027-05-10'),
    currentLocation: 'Trạm điều hành NT2',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300',
    joinedDate: new Date('2023-11-20'),
    notes: 'Lái xe bán tải đưa đón chuyên gia nông nghiệp & giám sát lô',
    enterprise: 'Nông trường 2',
    team: 'Tổ Điều hành',
    position: 'Lái xe bán tải công vụ',
    idCardNumber: '079092009012',
    idCardIssueDate: '2022-08-25',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'huy.lq@thacoagri.vn',
  },
  {
    code: 'TA-NV-1005',
    username: 'driver.khang.hv',
    fullName: 'Hoàng Văn Khang',
    phone: '0938 112 233',
    unit: Unit.XN_BO,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_C,
    licenseNumber: '790270415263',
    licenseExpiryDate: new Date('2028-10-18'),
    healthCheckExpiryDate: new Date('2026-12-20'),
    currentLocation: 'Chuồng bò A2 ➔ Bãi ủ chua cỏ voi',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300',
    joinedDate: new Date('2022-01-10'),
    notes: 'Lái xe ben Howo chở cỏ ủ chua & phụ phẩm bã bia',
    enterprise: 'Xí nghiệp Bò',
    team: 'Đội Xe ben 10T',
    position: 'Lái xe ben',
    idCardNumber: '079089010123',
    idCardIssueDate: '2020-12-10',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'khang.hv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1006',
    username: 'driver.trong.vd',
    fullName: 'Vũ Đình Trọng',
    phone: '0979 556 677',
    unit: Unit.BAN_CO_GIOI,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_FC,
    licenseNumber: '790281526374',
    licenseExpiryDate: new Date('2027-11-12'),
    healthCheckExpiryDate: new Date('2026-10-05'),
    currentLocation: 'Kho Tổng Koun Mom ➔ Cửa khẩu Hoa Lư',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300',
    joinedDate: new Date('2021-07-20'),
    notes: 'Chuyên tuyến xuất khẩu nông sản chuối sang Việt Nam',
    enterprise: 'Ban Cơ giới',
    team: 'Đội Xe Container',
    position: 'Lái xe đầu kéo',
    idCardNumber: '079088011234',
    idCardIssueDate: '2020-03-14',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'trong.vd@thacoagri.vn',
  },
  {
    code: 'TA-NV-1007',
    username: 'driver.tung.pt',
    fullName: 'Phan Thanh Tùng',
    phone: '0985 667 788',
    unit: Unit.TT_BTSC,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.SAN_SANG,
    licenseClass: DriverLicenseClass.BANG_MAY_NONG_NGHIEP,
    licenseNumber: 'NN-2023-99182',
    licenseExpiryDate: new Date('2028-06-25'),
    healthCheckExpiryDate: new Date('2027-02-28'),
    currentLocation: 'Xưởng BTSC (Chạy thử máy sau đại tu)',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300',
    joinedDate: new Date('2022-09-15'),
    notes: 'Kỹ thuật viên nghiệm thu vận hành thử máy kéo sau khi đại tu',
    enterprise: 'Trung tâm BTSC',
    team: 'Tổ Thử nghiệm máy',
    position: 'Thợ máy kiêm Vận hành thử',
    idCardNumber: '079090012345',
    idCardIssueDate: '2021-07-22',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'tung.pt@thacoagri.vn',
  },
  {
    code: 'TA-NV-1008',
    username: 'driver.tri.dm',
    fullName: 'Đỗ Minh Trí',
    phone: '0909 332 211',
    unit: Unit.NT1,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_C,
    licenseNumber: '790292637485',
    licenseExpiryDate: new Date('2029-02-18'),
    healthCheckExpiryDate: new Date('2026-11-30'),
    currentLocation: 'Kho bao bì ➔ Trạm đóng gói NT1',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300',
    joinedDate: new Date('2023-01-15'),
    notes: 'Vận chuyển thùng carton đóng gói & vật tư nông nghiệp',
    enterprise: 'Nông trường 1',
    team: 'Đội Vận tải',
    position: 'Lái xe tải',
    idCardNumber: '079093013456',
    idCardIssueDate: '2022-11-10',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'tri.dm@thacoagri.vn',
  },
  {
    code: 'TA-NV-1009',
    username: 'driver.an.nv',
    fullName: 'Nguyễn Văn An',
    phone: '0913 221 144',
    unit: Unit.NT2,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_FC,
    licenseNumber: '790303748596',
    licenseExpiryDate: new Date('2027-10-05'),
    healthCheckExpiryDate: new Date('2026-10-15'), // Sắp hết hạn 60 ngày (Alert)
    currentLocation: 'NT2 ➔ Kho mát Tổng KLH Koun Mom',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300',
    joinedDate: new Date('2021-12-01'),
    notes: 'Lái xe đầu kéo chở mooc lạnh bảo quản chuối tươi',
    enterprise: 'Nông trường 2',
    team: 'Đội Xe Container',
    position: 'Lái xe đầu kéo',
    idCardNumber: '079085014567',
    idCardIssueDate: '2019-10-15',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'an.nv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1010',
    username: 'driver.binh.tv',
    fullName: 'Trần Văn Bình',
    phone: '0968 445 577',
    unit: Unit.BAN_CO_GIOI,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.SAN_SANG,
    licenseClass: DriverLicenseClass.HANG_B2,
    licenseNumber: '790314859607',
    licenseExpiryDate: new Date('2030-01-20'),
    healthCheckExpiryDate: new Date('2027-03-15'),
    currentLocation: 'Bãi Xe Trung Tâm',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300',
    joinedDate: new Date('2023-04-10'),
    notes: 'Lái xe bán tải phục vụ công tác đối ngoại & hành chính',
    enterprise: 'Ban Cơ giới',
    team: 'Tổ Xe Công vụ',
    position: 'Lái xe công vụ',
    idCardNumber: '079091015678',
    idCardIssueDate: '2022-04-18',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'binh.tv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1011',
    username: 'driver.chinh.lv',
    fullName: 'Lê Văn Chính',
    phone: '0982 778 899',
    unit: Unit.XN_BO,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.BANG_MAY_NONG_NGHIEP,
    licenseNumber: 'NN-2022-88192',
    licenseExpiryDate: new Date('2028-09-14'),
    healthCheckExpiryDate: new Date('2027-01-10'),
    currentLocation: 'Cánh đồng cỏ voi XN Bò (Đang cắt cỏ tươi)',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300',
    joinedDate: new Date('2022-06-18'),
    notes: 'Thợ vận hành máy cắt cỏ liên hợp & máy cuộn rơm',
    enterprise: 'Xí nghiệp Bò',
    team: 'Đội Cơ giới Trồng cỏ',
    position: 'Thợ vận hành máy gặt cắt cỏ',
    idCardNumber: '079088016789',
    idCardIssueDate: '2020-05-20',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'chinh.lv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1012',
    username: 'driver.dung.pv',
    fullName: 'Phạm Văn Dũng',
    phone: '0937 665 544',
    unit: Unit.TT_BTSC,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_C,
    licenseNumber: '790325960718',
    licenseExpiryDate: new Date('2029-04-22'),
    healthCheckExpiryDate: new Date('2026-11-18'),
    currentLocation: 'Lô A05 (Đang cẩu kéo máy cày sự cố)',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
    joinedDate: new Date('2021-10-15'),
    notes: 'Chuyên gia cứu hộ lầy ruộng & kéo phương tiện gặp sự cố',
    enterprise: 'Trung tâm BTSC',
    team: 'Đội Xe Cẩu & Cứu hộ',
    position: 'Lái xe cẩu cứu hộ',
    idCardNumber: '079087017890',
    idCardIssueDate: '2019-12-14',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'dung.pv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1013',
    username: 'driver.em.hv',
    fullName: 'Hoàng Văn Em',
    phone: '0906 114 477',
    unit: Unit.NT1,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.DANG_VAN_HANH,
    licenseClass: DriverLicenseClass.HANG_FC,
    licenseNumber: '790336071829',
    licenseExpiryDate: new Date('2028-02-10'),
    healthCheckExpiryDate: new Date('2026-12-05'),
    currentLocation: 'Trạm đóng gói NT1 ➔ Kho lạnh',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300',
    joinedDate: new Date('2022-03-01'),
    notes: 'Lái xe đầu kéo chở nông sản chuối xuất khẩu chất lượng cao',
    enterprise: 'Nông trường 1',
    team: 'Đội Xe Container',
    position: 'Lái xe đầu kéo',
    idCardNumber: '079090018901',
    idCardIssueDate: '2021-04-10',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'em.hv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1014',
    username: 'driver.giang.vv',
    fullName: 'Vũ Văn Giang',
    phone: '0975 889 900',
    unit: Unit.NT2,
    employmentStatus: DriverEmploymentStatus.DANG_LAM_VIEC,
    currentShiftStatus: DriverShiftStatus.SAN_SANG,
    licenseClass: DriverLicenseClass.HANG_B2,
    licenseNumber: '790347182930',
    licenseExpiryDate: new Date('2030-07-15'),
    healthCheckExpiryDate: new Date('2027-04-20'),
    currentLocation: 'Bãi xe NT2',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300',
    joinedDate: new Date('2023-09-10'),
    notes: 'Lái xe tuần tra bảo vệ an ninh nông trường chuối',
    enterprise: 'Nông trường 2',
    team: 'Tổ Xe Công vụ',
    position: 'Lái xe bán tải',
    idCardNumber: '079093019012',
    idCardIssueDate: '2022-10-15',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'giang.vv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1015',
    username: 'driver.hai.dv',
    fullName: 'Đỗ Văn Hải',
    phone: '0981 776 655',
    unit: Unit.NT1,
    employmentStatus: DriverEmploymentStatus.DA_NGHI_VIEC,
    currentShiftStatus: null,
    licenseClass: DriverLicenseClass.BANG_MAY_NONG_NGHIEP,
    licenseNumber: 'NN-2022-33441',
    licenseExpiryDate: new Date('2027-03-12'),
    healthCheckExpiryDate: new Date('2026-05-01'), // Quá hạn (Alert)
    currentLocation: null,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300',
    joinedDate: new Date('2022-03-12'),
    resignedDate: new Date('2026-06-15'),
    resignedReason: 'Chấm dứt HĐLĐ theo nguyện vọng cá nhân (chuyển về quê)',
    notes: 'Đã hoàn tất bàn giao máy cày và công nợ dụng cụ phụ tùng.',
    enterprise: 'Nông trường 1',
    team: 'Đội Cơ giới Nông trường 1',
    position: 'Thợ vận hành máy cày',
    idCardNumber: '079086020123',
    idCardIssueDate: '2020-02-10',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'hai.dv@thacoagri.vn',
  },
  {
    code: 'TA-NV-1016',
    username: 'driver.hung.nv2',
    fullName: 'Ngô Văn Hùng',
    phone: '0903 112 334',
    unit: Unit.BAN_CO_GIOI,
    employmentStatus: DriverEmploymentStatus.DA_NGHI_VIEC,
    currentShiftStatus: null,
    licenseClass: DriverLicenseClass.HANG_FC,
    licenseNumber: 'FC-92-998811',
    licenseExpiryDate: new Date('2026-08-05'), // Đã hết hạn (Alert)
    healthCheckExpiryDate: new Date('2026-03-10'),
    currentLocation: null,
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300',
    joinedDate: new Date('2021-08-05'),
    resignedDate: new Date('2026-04-30'),
    resignedReason: 'Hết hạn hợp đồng lao động 3 năm',
    notes: 'Đã bàn giao đầu kéo Container 92C-14772 cho phòng Cơ Giới.',
    enterprise: 'Ban Cơ giới',
    team: 'Đội Xe Container Đường dài',
    position: 'Lái xe đầu kéo',
    idCardNumber: '079084021234',
    idCardIssueDate: '2019-06-25',
    idCardIssuePlace: 'Cục CS QLHC về TTXH',
    email: 'hung.ngo@thacoagri.vn',
  },
];

async function main() {
  console.log('🚀 Đang đồng bộ 25 hồ sơ lái xe & thợ vận hành vào MySQL database...');
  const salt = await bcrypt.genSalt(10);
  const passwordHash = await bcrypt.hash('123456', salt);

  for (const item of DRIVER_SEEDS) {
    // 1. Upsert User
    const user = await prisma.user.upsert({
      where: { code: item.code },
      update: {
        fullName: item.fullName,
        phone: item.phone,
        unit: item.unit,
        employmentStatus: item.employmentStatus,
        currentShiftStatus: item.currentShiftStatus,
        licenseClass: item.licenseClass,
        licenseNumber: item.licenseNumber,
        licenseExpiryDate: item.licenseExpiryDate,
        healthCheckExpiryDate: item.healthCheckExpiryDate,
        currentLocation: item.currentLocation,
        avatarUrl: item.avatarUrl,
        joinedDate: item.joinedDate,
        resignedDate: (item as any).resignedDate || null,
        resignedReason: (item as any).resignedReason || null,
        notes: item.notes,
      },
      create: {
        code: item.code,
        username: item.username,
        passwordHash,
        fullName: item.fullName,
        phone: item.phone,
        role: Role.DRIVER,
        unit: item.unit,
        employmentStatus: item.employmentStatus,
        currentShiftStatus: item.currentShiftStatus,
        licenseClass: item.licenseClass,
        licenseNumber: item.licenseNumber,
        licenseExpiryDate: item.licenseExpiryDate,
        healthCheckExpiryDate: item.healthCheckExpiryDate,
        currentLocation: item.currentLocation,
        avatarUrl: item.avatarUrl,
        joinedDate: item.joinedDate,
        resignedDate: (item as any).resignedDate || null,
        resignedReason: (item as any).resignedReason || null,
        notes: item.notes,
      },
    });

    // 2. Upsert EmployeeRecord
    await prisma.employeeRecord.upsert({
      where: { empCode: item.code },
      update: {
        fullName: item.fullName,
        phone: item.phone,
        email: item.email,
        businessUnit: item.enterprise,
        enterprise: item.enterprise,
        complex: 'Snoul (Campuchia)',
        farm: item.enterprise,
        team: item.team,
        position: item.position,
        licenseClass: item.licenseClass,
        licenseNumber: item.licenseNumber,
        licenseExpiryDate: item.licenseExpiryDate ? item.licenseExpiryDate.toISOString().slice(0, 10) : null,
        healthCheckExpiryDate: item.healthCheckExpiryDate ? item.healthCheckExpiryDate.toISOString().slice(0, 10) : null,
        status: item.employmentStatus === DriverEmploymentStatus.DANG_LAM_VIEC ? 'Hoạt động' : 'Đã nghỉ việc',
        idCardNumber: item.idCardNumber,
        idCardIssueDate: item.idCardIssueDate,
        idCardIssuePlace: item.idCardIssuePlace,
        joinedDate: item.joinedDate.toISOString().slice(0, 10),
      },
      create: {
        empCode: item.code,
        fullName: item.fullName,
        phone: item.phone,
        email: item.email,
        businessUnit: item.enterprise,
        enterprise: item.enterprise,
        complex: 'Snoul (Campuchia)',
        farm: item.enterprise,
        team: item.team,
        position: item.position,
        licenseClass: item.licenseClass,
        licenseNumber: item.licenseNumber,
        licenseExpiryDate: item.licenseExpiryDate ? item.licenseExpiryDate.toISOString().slice(0, 10) : null,
        healthCheckExpiryDate: item.healthCheckExpiryDate ? item.healthCheckExpiryDate.toISOString().slice(0, 10) : null,
        status: item.employmentStatus === DriverEmploymentStatus.DANG_LAM_VIEC ? 'Hoạt động' : 'Đã nghỉ việc',
        idCardNumber: item.idCardNumber,
        idCardIssueDate: item.idCardIssueDate,
        idCardIssuePlace: item.idCardIssuePlace,
        joinedDate: item.joinedDate.toISOString().slice(0, 10),
      },
    });
  }

  console.log('✅ Đã lưu thành công 25 hồ sơ lái xe & nhân viên vào database MySQL!');
}

main()
  .catch((e) => {
    console.error('❌ Lỗi seed drivers:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
