import {
  KLHUnit,
  VehicleGPS,
  GeofenceZone,
  GPSOfflineLog,
  VehicleProfile,
  EquipmentProfile,
  GPSSensorDevice,
  ProductionPlan,
  DispatchOrder,
  WeightTicket,
  DriverProfile,
  DriverViolation,
  MaintenancePlan,
  WorkOrder,
  FuelVoucher,
  FuelTankStorage,
  FuelDropAlert,
  SystemAlert,
  ProductivityReportItem,
  MasterUnit,
  MasterVehicleType,
  SystemUser,
  AuditLogItem,
} from '../types';

export const KLH_UNITS: KLHUnit[] = [
  { id: 'ALL', name: 'Tất cả Khu liên hợp', code: 'ALL', region: 'Tổng thể', totalVehicles: 3204 },
  { id: 'KOUN_MOM', name: 'Khu liên hợp Koun Mom', code: 'KLH-KM', region: 'Ratanakiri, Campuchia', totalVehicles: 1263 },
  { id: 'SNOUL', name: 'Khu liên hợp Snoul', code: 'KLH-SN', region: 'Kratie, Campuchia', totalVehicles: 1035 },
  { id: 'NAM_LAO', name: 'Khu liên hợp Nam Lào', code: 'KLH-NL', region: 'Attapeu, Lào', totalVehicles: 906 },
];

export const MOCK_GPS_VEHICLES: VehicleGPS[] = [
  {
    id: 'V001',
    plateNumber: '70C-128.45',
    code: 'TA-SN-042',
    driverName: 'Nguyễn Văn Hùng',
    driverPhone: '0988 123 456',
    vehicleType: 'Xe kéo rơ-moóc',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    subUnit: 'Nông trường Chuối 01',
    status: 'running',
    speed: 38,
    engineRpm: 1850,
    fuelLevelPercent: 78,
    fuelLiters: 195,
    temperature: 84,
    lat: 12.0542,
    lng: 106.5821,
    address: 'Lô C12 - Trục đường D4, NT Chuối 01, Snoul',
    heading: 120,
    lastUpdated: '10 giây trước',
    todayKm: 64.5,
    todayEngineHours: 5.2,
  },
  {
    id: 'V002',
    plateNumber: '81A-049.21',
    code: 'TA-KM-108',
    driverName: 'Sokha Chamnan',
    driverPhone: '+855 88 765 4321',
    vehicleType: 'Máy cày nông nghiệp',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    subUnit: 'Đội Cơ giới Làm đất 02',
    status: 'running',
    speed: 14,
    engineRpm: 2200,
    fuelLevelPercent: 62,
    fuelLiters: 93,
    temperature: 88,
    lat: 13.5621,
    lng: 106.9845,
    address: 'Thửa đất Lô B8 - Khu vực xới đất sâu Koun Mom',
    heading: 45,
    lastUpdated: '25 giây trước',
    todayKm: 28.2,
    todayEngineHours: 6.8,
  },
  {
    id: 'V003',
    plateNumber: '70C-198.88',
    code: 'TA-SN-015',
    driverName: 'Trần Minh Đức',
    driverPhone: '0977 456 789',
    vehicleType: 'Xe tải ben 15T',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    subUnit: 'Đội Vận chuyển Vật tư',
    status: 'idling',
    speed: 0,
    engineRpm: 750,
    fuelLevelPercent: 88,
    fuelLiters: 220,
    temperature: 79,
    lat: 12.0611,
    lng: 106.5912,
    address: 'Cổng Trạm Cân Điện Tử số 2, Snoul',
    heading: 0,
    lastUpdated: '1 phút trước',
    todayKm: 89.0,
    todayEngineHours: 4.5,
  },
  {
    id: 'V004',
    plateNumber: '81C-076.54',
    code: 'TA-IP-033',
    driverName: 'Lê Hoàng Long',
    driverPhone: '0912 345 678',
    vehicleType: 'Xe bồn tưới dinh dưỡng',
    klhName: 'Khu liên hợp Ia Puch (Gia Lai)',
    subUnit: 'Xí nghiệp Cây ăn trái 03',
    status: 'running',
    speed: 25,
    engineRpm: 1600,
    fuelLevelPercent: 45,
    fuelLiters: 112,
    temperature: 82,
    lat: 13.7254,
    lng: 107.8214,
    address: 'Lô Sầu Riêng R-05, XN Ia Puch',
    heading: 270,
    lastUpdated: '5 giây trước',
    todayKm: 42.1,
    todayEngineHours: 4.0,
  },
  {
    id: 'V005',
    plateNumber: '70C-234.11',
    code: 'TA-SN-099',
    driverName: 'Phạm Quốc Bảo',
    driverPhone: '0909 888 999',
    vehicleType: 'Xe kéo rơ-moóc',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    subUnit: 'Nông trường Chuối 03',
    status: 'maintenance',
    speed: 0,
    engineRpm: 0,
    fuelLevelPercent: 30,
    fuelLiters: 75,
    temperature: 32,
    lat: 12.0489,
    lng: 106.5744,
    address: 'Khu Vực Cầu Nâng Xưởng BTSC Trung Tâm Snoul',
    heading: 0,
    lastUpdated: '15 phút trước',
    todayKm: 0,
    todayEngineHours: 0,
  },
  {
    id: 'V006',
    plateNumber: '81C-112.90',
    code: 'TA-KM-055',
    driverName: 'Chan Vanna',
    driverPhone: '+855 97 123 9999',
    vehicleType: 'Máy xúc đào bánh xích',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    subUnit: 'Đội Thủy lợi Đắp mương',
    status: 'running',
    speed: 4,
    engineRpm: 2100,
    fuelLevelPercent: 55,
    fuelLiters: 138,
    temperature: 86,
    lat: 13.5789,
    lng: 106.9912,
    address: 'Kênh thủy lợi T3 - Nông trường Cao su Koun Mom',
    heading: 180,
    lastUpdated: '18 giây trước',
    todayKm: 6.4,
    todayEngineHours: 7.2,
  },
  {
    id: 'V007',
    plateNumber: '70C-099.12',
    code: 'TA-SN-081',
    driverName: 'Đinh Xuân Thành',
    driverPhone: '0933 555 777',
    vehicleType: 'Xe bán tải tuần tra',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    subUnit: 'Ban An ninh Bảo vệ',
    status: 'running',
    speed: 48,
    engineRpm: 1950,
    fuelLevelPercent: 70,
    fuelLiters: 56,
    temperature: 81,
    lat: 12.0722,
    lng: 106.5612,
    address: 'Đường vành đai bảo vệ ranh giới Lô E Snoul',
    heading: 310,
    lastUpdated: '8 giây trước',
    todayKm: 112.0,
    todayEngineHours: 5.8,
  },
  {
    id: 'V008',
    plateNumber: '81B-008.33',
    code: 'TA-IP-004',
    driverName: 'Vũ Đình Trọng',
    driverPhone: '0966 222 333',
    vehicleType: 'Xe chở công nhân 29 chỗ',
    klhName: 'Khu liên hợp Ia Puch (Gia Lai)',
    subUnit: 'Đội Xe Đưa đón Hành chính',
    status: 'stopped',
    speed: 0,
    engineRpm: 0,
    fuelLevelPercent: 82,
    fuelLiters: 100,
    temperature: 30,
    lat: 13.7198,
    lng: 107.8345,
    address: 'Bãi đỗ xe Ký túc xá Cán bộ Công nhân viên Ia Puch',
    heading: 90,
    lastUpdated: '32 phút trước',
    todayKm: 34.0,
    todayEngineHours: 1.8,
  }
];

export const MOCK_GEOFENCES: GeofenceZone[] = [
  {
    id: 'GEO-01',
    name: 'Vùng canh tác Nông trường Chuối 01',
    code: 'GEO-SN-CH01',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    zoneType: 'plot',
    areaHectares: 450,
    maxSpeedKmH: 30,
    activeVehiclesCount: 18,
    alertOnExit: true,
    alertOnEntry: false,
    status: 'active',
  },
  {
    id: 'GEO-02',
    name: 'Xưởng BTSC & Kho Vật tư Trung Tâm',
    code: 'GEO-SN-BTSC',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    zoneType: 'workshop',
    areaHectares: 15,
    maxSpeedKmH: 15,
    activeVehiclesCount: 8,
    alertOnExit: false,
    alertOnEntry: false,
    status: 'active',
  },
  {
    id: 'GEO-03',
    name: 'Khu bồn cấp nhiên liệu Trạm số 1',
    code: 'GEO-SN-FUEL01',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    zoneType: 'fuel_station',
    areaHectares: 4.5,
    maxSpeedKmH: 10,
    activeVehiclesCount: 3,
    alertOnExit: false,
    alertOnEntry: true,
    status: 'active',
  },
  {
    id: 'GEO-04',
    name: 'Khu vực Lô Rừng phòng hộ (Vùng cấm)',
    code: 'GEO-KM-RESTRICTED',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    zoneType: 'restricted',
    areaHectares: 620,
    maxSpeedKmH: 0,
    activeVehiclesCount: 0,
    alertOnExit: false,
    alertOnEntry: true,
    status: 'active',
  },
];

export const MOCK_OFFLINE_LOGS: GPSOfflineLog[] = [
  {
    id: 'OFF-001',
    plateNumber: '70C-144.22',
    driverName: 'Nguyễn Văn Hải',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    lostSignalTime: '2026-08-26 06:15:00',
    reconnectedTime: '2026-08-26 07:42:00',
    durationMinutes: 87,
    lastKnownLocation: 'Lô Cao su giáp ranh suối O’Krieng (vùng lõm sóng)',
    reason: 'Vào vùng trũng hẻo lánh',
    status: 'resolved',
  },
  {
    id: 'OFF-002',
    plateNumber: '81C-098.11',
    driverName: 'Lý Quốc Cường',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    lostSignalTime: '2026-08-26 05:30:00',
    reconnectedTime: 'Chưa kết nối lại',
    durationMinutes: 135,
    lastKnownLocation: 'Khu mương D5 Nông trường Koun Mom',
    reason: 'Rút thiết bị GPS',
    status: 'unresolved',
  },
  {
    id: 'OFF-003',
    plateNumber: '81C-054.89',
    driverName: 'Đặng Tuấn Anh',
    klhName: 'Khu liên hợp Ia Puch (Gia Lai)',
    lostSignalTime: '2026-08-25 18:20:00',
    reconnectedTime: '2026-08-25 18:55:00',
    durationMinutes: 35,
    lastKnownLocation: 'Trạm điện mặt trời Ia Puch',
    reason: 'Mất sóng 4G/GSM',
    status: 'resolved',
  }
];

export const MOCK_VEHICLE_PROFILES: VehicleProfile[] = [
  {
    id: 'VP-001',
    plateNumber: '70C-128.45',
    internalCode: 'TA-SN-042',
    vehicleCategory: 'Xe kéo rơ-moóc',
    brandModel: 'THACO AUMAN EST 400',
    yearManufactured: 2023,
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    teamUnit: 'Nông trường Chuối 01',
    currentDriver: 'Nguyễn Văn Hùng',
    status: 'active',
    currentOdoKm: 48250,
    currentEngineHours: 3210,
    gpsImei: '864219041288491',
    fuelSensorImei: 'FL-SN-042-99',
    inspectionExpiry: '2027-02-15',
    insuranceExpiry: '2027-01-20',
  },
  {
    id: 'VP-002',
    plateNumber: '81A-049.21',
    internalCode: 'TA-KM-108',
    vehicleCategory: 'Máy cày nông nghiệp',
    brandModel: 'KUBOTA M7040 KDH 4WD',
    yearManufactured: 2022,
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    teamUnit: 'Đội Cơ giới Làm đất 02',
    currentDriver: 'Sokha Chamnan',
    status: 'active',
    currentOdoKm: 18400,
    currentEngineHours: 4520,
    gpsImei: '864219049912003',
    fuelSensorImei: 'FL-KM-108-12',
    inspectionExpiry: '2026-11-30',
    insuranceExpiry: '2026-12-10',
  },
  {
    id: 'VP-003',
    plateNumber: '70C-198.88',
    internalCode: 'TA-SN-015',
    vehicleCategory: 'Xe tải ben',
    brandModel: 'THACO FORLAND FD900',
    yearManufactured: 2024,
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    teamUnit: 'Đội Vận chuyển Vật tư',
    currentDriver: 'Trần Minh Đức',
    status: 'active',
    currentOdoKm: 29400,
    currentEngineHours: 1980,
    gpsImei: '864219051829304',
    fuelSensorImei: 'FL-SN-015-88',
    inspectionExpiry: '2027-06-25',
    insuranceExpiry: '2027-05-18',
  },
  {
    id: 'VP-004',
    plateNumber: '70C-234.11',
    internalCode: 'TA-SN-099',
    vehicleCategory: 'Xe kéo rơ-moóc',
    brandModel: 'HOWO SINOTRUK T7H',
    yearManufactured: 2021,
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    teamUnit: 'Nông trường Chuối 03',
    currentDriver: 'Phạm Quốc Bảo',
    status: 'maintenance',
    currentOdoKm: 98120,
    currentEngineHours: 6490,
    gpsImei: '864219030018273',
    fuelSensorImei: 'FL-SN-099-01',
    inspectionExpiry: '2026-09-10',
    insuranceExpiry: '2026-09-01',
  },
  {
    id: 'VP-005',
    plateNumber: '81C-076.54',
    internalCode: 'TA-IP-033',
    vehicleCategory: 'Xe bồn tưới',
    brandModel: 'ISUZU FVR 900 VẬN HÀNH BỒN 8M3',
    yearManufactured: 2023,
    klhName: 'Khu liên hợp Ia Puch (Gia Lai)',
    teamUnit: 'Xí nghiệp Cây ăn trái 03',
    currentDriver: 'Lê Hoàng Long',
    status: 'active',
    currentOdoKm: 34100,
    currentEngineHours: 2450,
    gpsImei: '864219077281920',
    fuelSensorImei: 'FL-IP-033-54',
    inspectionExpiry: '2027-04-12',
    insuranceExpiry: '2027-03-30',
  }
];

export const MOCK_DISPATCH_ORDERS: DispatchOrder[] = [
  {
    id: 'DO-2026-0826-01',
    orderCode: 'LĐX-SN-0826-001',
    orderType: 'Vận chuyển nông sản',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    fromLocation: 'Nhà đóng gói Chuối Packhouse 04',
    toLocation: 'Cửa khẩu Quốc tế Hoa Lư (Bình Phước)',
    plateNumber: '70C-128.45',
    vehicleType: 'Xe kéo rơ-moóc lạnh',
    driverName: 'Nguyễn Văn Hùng',
    cargoDescription: 'Chuối tươi xuất khẩu đóng thùng lạnh (Container 40ft)',
    plannedWeightTons: 22.5,
    actualWeightTons: 22.48,
    startTime: '06:00',
    endTime: '11:30',
    progressPercent: 65,
    status: 'running',
  },
  {
    id: 'DO-2026-0826-02',
    orderCode: 'LĐX-KM-0826-002',
    orderType: 'Làm đất xới cày',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    fromLocation: 'Bãi máy xới trung tâm',
    toLocation: 'Lô B8 - Khu mở rộng trồng mới',
    plateNumber: '81A-049.21',
    vehicleType: 'Máy cày nông nghiệp',
    driverName: 'Sokha Chamnan',
    cargoDescription: 'Xới đất lần 2 độ sâu 40cm chuẩn bị xuống giống',
    plannedWeightTons: 0,
    actualWeightTons: 0,
    startTime: '05:30',
    endTime: '17:00',
    progressPercent: 78,
    status: 'running',
  },
  {
    id: 'DO-2026-0826-03',
    orderCode: 'LĐX-SN-0826-003',
    orderType: 'Cấp phát vật tư phân bón',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    fromLocation: 'Kho Vật tư Tổng KLH Snoul',
    toLocation: 'Điểm tập kết NT Chuối 02',
    plateNumber: '70C-198.88',
    vehicleType: 'Xe tải ben 15T',
    driverName: 'Trần Minh Đức',
    cargoDescription: 'Phân bón hữu cơ vi sinh dạng bao (300 bao)',
    plannedWeightTons: 15.0,
    actualWeightTons: 15.12,
    startTime: '07:00',
    endTime: '09:45',
    progressPercent: 100,
    status: 'completed',
  },
  {
    id: 'DO-2026-0826-04',
    orderCode: 'LĐX-IP-0826-004',
    orderType: 'Phun tưới dinh dưỡng',
    klhName: 'Khu liên hợp Ia Puch (Gia Lai)',
    fromLocation: 'Trạm phối trộn dinh dưỡng TT',
    toLocation: 'Lô Sầu Riêng R-05',
    plateNumber: '81C-076.54',
    vehicleType: 'Xe bồn tưới dinh dưỡng',
    driverName: 'Lê Hoàng Long',
    cargoDescription: 'Dung dịch Amino Acid tưới gốc cây ăn trái (8000L)',
    plannedWeightTons: 8.0,
    actualWeightTons: 8.0,
    startTime: '06:30',
    endTime: '11:00',
    progressPercent: 50,
    status: 'running',
  }
];

export const MOCK_WEIGHT_TICKETS: WeightTicket[] = [
  {
    id: 'WT-001',
    ticketCode: 'PC-SN-2608-019',
    scaleStationName: 'Trạm Cân Điện Tử 80T - Packhouse 04',
    dispatchOrderCode: 'LĐX-SN-0826-001',
    plateNumber: '70C-128.45',
    driverName: 'Nguyễn Văn Hùng',
    cargoType: 'Chuối tươi xuất khẩu container',
    grossWeightKg: 38480,
    tareWeightKg: 16000,
    netWeightKg: 22480,
    scaleTimeIn: '2026-08-26 06:45:00',
    scaleTimeOut: '2026-08-26 07:10:00',
    weighMaster: 'Hoàng Kim Dung',
    status: 'confirmed',
  },
  {
    id: 'WT-002',
    ticketCode: 'PC-SN-2608-020',
    scaleStationName: 'Trạm Cân Kho Vật Tư Snoul',
    dispatchOrderCode: 'LĐX-SN-0826-003',
    plateNumber: '70C-198.88',
    driverName: 'Trần Minh Đức',
    cargoType: 'Phân bón hữu cơ vi sinh',
    grossWeightKg: 24120,
    tareWeightKg: 9000,
    netWeightKg: 15120,
    scaleTimeIn: '2026-08-26 07:20:00',
    scaleTimeOut: '2026-08-26 07:40:00',
    weighMaster: 'Vũ Thị Ngọc',
    status: 'confirmed',
  }
];

export const MOCK_DRIVERS: DriverProfile[] = [
  {
    id: 'DRV-001',
    employeeCode: 'TA-NV-1082',
    fullName: 'Nguyễn Văn Hùng',
    phone: '0988 123 456',
    rfidCardNumber: 'E280116060000204',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    teamUnit: 'Nông trường Chuối 01',
    licenseNumber: '790182736412',
    licenseClass: 'FC',
    licenseExpiry: '2028-05-12',
    healthCheckExpiry: '2027-03-20',
    assignedVehicle: '70C-128.45',
    safetyScore: 98,
    totalTripsMonth: 44,
    fuelEfficiencyRate: 104.2,
    status: 'on_shift',
  },
  {
    id: 'DRV-002',
    employeeCode: 'TA-NV-2091',
    fullName: 'Sokha Chamnan',
    phone: '+855 88 765 4321',
    rfidCardNumber: 'E280116060000305',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    teamUnit: 'Đội Cơ giới Làm đất 02',
    licenseNumber: 'CAM-8829104',
    licenseClass: 'Chứng chỉ cơ giới',
    licenseExpiry: '2027-10-18',
    healthCheckExpiry: '2027-01-15',
    assignedVehicle: '81A-049.21',
    safetyScore: 95,
    totalTripsMonth: 38,
    fuelEfficiencyRate: 99.1,
    status: 'on_shift',
  },
  {
    id: 'DRV-003',
    employeeCode: 'TA-NV-1104',
    fullName: 'Trần Minh Đức',
    phone: '0977 456 789',
    rfidCardNumber: 'E280116060000412',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    teamUnit: 'Đội Vận chuyển Vật tư',
    licenseNumber: '790192847163',
    licenseClass: 'C',
    licenseExpiry: '2026-09-28', // Sắp hết hạn < 60 ngày
    healthCheckExpiry: '2026-09-15',
    assignedVehicle: '70C-198.88',
    safetyScore: 92,
    totalTripsMonth: 52,
    fuelEfficiencyRate: 98.4,
    status: 'on_shift',
  },
  {
    id: 'DRV-004',
    employeeCode: 'TA-NV-0988',
    fullName: 'Phạm Quốc Bảo',
    phone: '0909 888 999',
    rfidCardNumber: 'E280116060000555',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    teamUnit: 'Nông trường Chuối 03',
    licenseNumber: '790172635411',
    licenseClass: 'FC',
    licenseExpiry: '2029-01-10',
    healthCheckExpiry: '2027-04-10',
    assignedVehicle: '70C-234.11',
    safetyScore: 88,
    totalTripsMonth: 29,
    fuelEfficiencyRate: 95.0,
    status: 'available',
  }
];

export const MOCK_MAINTENANCE_PLANS: MaintenancePlan[] = [
  {
    id: 'MP-001',
    planCode: 'PM-250H-SN-042',
    plateNumber: '70C-128.45',
    vehicleType: 'Xe kéo rơ-moóc',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    maintenanceType: 'Bảo dưỡng 250 giờ',
    currentHours: 3210,
    dueHours: 3250,
    overdueHours: 0,
    scheduledDate: '2026-08-30',
    assignedTechnician: 'Lê Văn Cơ (Tổ trưởng Máy)',
    status: 'upcoming',
  },
  {
    id: 'MP-002',
    planCode: 'PM-500H-KM-108',
    plateNumber: '81A-049.21',
    vehicleType: 'Máy cày nông nghiệp',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    maintenanceType: 'Bảo dưỡng 500 giờ',
    currentHours: 4520,
    dueHours: 4500,
    overdueHours: 20, // Quá hạn 20h
    scheduledDate: '2026-08-25',
    assignedTechnician: 'Neth Sok (Thợ sửa chữa)',
    status: 'overdue',
  },
  {
    id: 'MP-003',
    planCode: 'PM-1000H-SN-099',
    plateNumber: '70C-234.11',
    vehicleType: 'Xe kéo rơ-moóc',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    maintenanceType: 'Đại tu động cơ',
    currentHours: 6490,
    dueHours: 6500,
    overdueHours: 0,
    scheduledDate: '2026-08-26',
    assignedTechnician: 'Nguyễn Tấn Đạt (Xưởng trưởng)',
    status: 'in_progress',
  }
];

export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'WO-001',
    orderCode: 'SC-SN-2608-001',
    plateNumber: '70C-234.11',
    vehicleType: 'HOWO T7H (Xe kéo)',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    issueDescription: 'Hệ thống turbo tăng áp phát tiếng kêu lớn, hao hụt công suất khi kéo tải nặng',
    priority: 'critical_sos',
    reportedBy: 'Phạm Quốc Bảo (Lái xe)',
    reportedDate: '2026-08-25 16:30',
    leadTechnician: 'Nguyễn Tấn Đạt',
    sparePartsCostVND: 14500000,
    laborHours: 12.5,
    currentStep: 'Đang sửa chữa',
    estimatedCompletion: '2026-08-27 15:00',
  },
  {
    id: 'WO-002',
    orderCode: 'SC-KM-2608-002',
    plateNumber: '81C-112.90',
    vehicleType: 'Máy xúc đào bánh xích',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    issueDescription: 'Rò rỉ dầu ty ô thủy lực cánh tay cần múc số 2',
    priority: 'high',
    reportedBy: 'Chan Vanna (Thợ máy)',
    reportedDate: '2026-08-26 07:15',
    leadTechnician: 'Neth Sok',
    sparePartsCostVND: 3800000,
    laborHours: 4.0,
    currentStep: 'Tiếp nhận',
    estimatedCompletion: '2026-08-26 17:00',
  },
  {
    id: 'WO-003',
    orderCode: 'SC-SN-2608-003',
    plateNumber: '70C-102.34',
    vehicleType: 'Máy cày New Holland',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    issueDescription: 'Thay thế vòng bi moay-ơ trục bánh sau và lọc gió động cơ',
    priority: 'medium',
    reportedBy: 'Võ Hùng Dũng',
    reportedDate: '2026-08-24 09:00',
    leadTechnician: 'Lê Văn Cơ',
    sparePartsCostVND: 5200000,
    laborHours: 6.0,
    currentStep: 'Chờ vật tư phụ tùng',
    estimatedCompletion: '2026-08-28 11:00',
  },
  {
    id: 'WO-004',
    orderCode: 'SC-IP-2608-004',
    plateNumber: '81A-003.55',
    vehicleType: 'Xe bán tải Ford Ranger',
    klhName: 'Khu liên hợp Ia Puch (Gia Lai)',
    issueDescription: 'Bảo dưỡng định kỳ 20,000km: thay dầu động cơ, lọc dầu, căn chỉnh thước lái',
    priority: 'low',
    reportedBy: 'Ngô Thanh Sơn',
    reportedDate: '2026-08-25 14:00',
    leadTechnician: 'Trần Văn Khang',
    sparePartsCostVND: 2100000,
    laborHours: 3.5,
    currentStep: 'Đã xuất xưởng',
    estimatedCompletion: '2026-08-26 09:00',
  }
];

export const MOCK_FUEL_VOUCHERS: FuelVoucher[] = [
  {
    id: 'FV-001',
    voucherCode: 'NL-SN-2608-0112',
    plateNumber: '70C-128.45',
    driverName: 'Nguyễn Văn Hùng',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    fuelStation: 'Trạm Xăng Dầu Trung Tâm Snoul 01',
    fuelType: 'DO 0.05S-II',
    litersPumped: 220.0,
    odoAtRefuelKm: 48250,
    engineHoursAtRefuel: 3210,
    pumpMeterBefore: 142850.0,
    pumpMeterAfter: 143070.0,
    refuelTime: '2026-08-26 05:45:00',
    dispenserStaff: 'Đỗ Mạnh Cường',
    status: 'verified',
  },
  {
    id: 'FV-002',
    voucherCode: 'NL-KM-2608-0098',
    plateNumber: '81A-049.21',
    driverName: 'Sokha Chamnan',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    fuelStation: 'Bồn Cấp Di Động Koun Mom',
    fuelType: 'DO 0.05S-II',
    litersPumped: 120.0,
    odoAtRefuelKm: 18400,
    engineHoursAtRefuel: 4520,
    pumpMeterBefore: 89400.0,
    pumpMeterAfter: 89520.0,
    refuelTime: '2026-08-26 05:20:00',
    dispenserStaff: 'Pheap Meng',
    status: 'verified',
  }
];

export const MOCK_FUEL_TANKS: FuelTankStorage[] = [
  {
    id: 'TANK-01',
    tankCode: 'BỒN-SN-01',
    tankName: 'Bồn Chứa Trung Tâm 01 (DO 0.05S-II)',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    capacityLiters: 50000,
    currentLiters: 38500,
    fillPercent: 77,
    safeMinLiters: 8000,
    lastImportDate: '2026-08-24 14:00',
    temperatureC: 28.5,
    status: 'normal',
  },
  {
    id: 'TANK-02',
    tankCode: 'BỒN-KM-01',
    tankName: 'Bồn Chứa Nông Trường Koun Mom',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    capacityLiters: 30000,
    currentLiters: 7200,
    fillPercent: 24,
    safeMinLiters: 6000,
    lastImportDate: '2026-08-18 10:30',
    temperatureC: 30.2,
    status: 'low_warning',
  }
];

export const MOCK_FUEL_DROP_ALERTS: FuelDropAlert[] = [
  {
    id: 'FDA-001',
    alertCode: 'SỤT-DẦU-SN-0825-01',
    plateNumber: '70C-188.02',
    driverName: 'Hoàng Văn Nam',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    droppedLiters: 42.5,
    durationMinutes: 6,
    dropTime: '2026-08-25 23:42:10',
    location: 'Bãi đất trống ngoài ranh giới Lô D Snoul',
    engineStatus: 'Đang tắt máy',
    suspectedCause: 'Hút trộm dầu trái phép',
    status: 'confirmed_theft',
  },
  {
    id: 'FDA-002',
    alertCode: 'SỤT-DẦU-KM-0826-02',
    plateNumber: '81C-066.33',
    driverName: 'Chorn Rithy',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    droppedLiters: 18.0,
    durationMinutes: 12,
    dropTime: '2026-08-26 03:15:00',
    location: 'Đường liên lô Koun Mom',
    engineStatus: 'Đang nổ cầm chừng',
    suspectedCause: 'Cảm biến dao động giả lập',
    status: 'investigating',
  }
];

export const MOCK_SYSTEM_ALERTS: SystemAlert[] = [
  {
    id: 'ALT-001',
    alertCode: 'SOS-SN-2608-01',
    severity: 'critical',
    category: 'SOS Khẩn cấp',
    plateNumber: '70C-234.11',
    driverName: 'Phạm Quốc Bảo',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    location: 'Đường nội bộ Lô Chuối C4 Snoul',
    description: 'Tài xế bấm nút SOS khẩn cấp: Xe bị bó cứng phanh trục sau gây trượt bánh nghiêng lề đường',
    occurredAt: '2026-08-26 07:12:00',
    acknowledgedBy: 'Trần Văn Mạnh (Điều phối viên)',
    status: 'handling',
  },
  {
    id: 'ALT-002',
    alertCode: 'SPD-SN-2608-02',
    severity: 'warning',
    category: 'Quá tốc độ',
    plateNumber: '70C-099.12',
    driverName: 'Đinh Xuân Thành',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    location: 'Đường Vành đai Nông trường Snoul',
    description: 'Phương tiện chạy 48 km/h vượt quá tốc độ cho phép của vùng nông trường (Tối đa 30 km/h)',
    occurredAt: '2026-08-26 07:35:10',
    status: 'unresolved',
  },
  {
    id: 'ALT-003',
    alertCode: 'GEO-KM-2608-03',
    severity: 'critical',
    category: 'Rời vùng Geofence',
    plateNumber: '81C-098.11',
    driverName: 'Lý Quốc Cường',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    location: 'Khu vực giáp ranh Lô Rừng Koun Mom',
    description: 'Phương tiện di chuyển ra khỏi ranh giới phân công mà không có Lệnh điều xe hợp lệ',
    occurredAt: '2026-08-26 05:45:00',
    status: 'unresolved',
  },
  {
    id: 'ALT-004',
    alertCode: 'TMP-IP-2608-04',
    severity: 'warning',
    category: 'Nhiệt độ động cơ cao',
    plateNumber: '81C-076.54',
    driverName: 'Lê Hoàng Long',
    klhName: 'Khu liên hợp Ia Puch (Gia Lai)',
    location: 'Lô Sầu Riêng R-05, Ia Puch',
    description: 'Cảm biến nhiệt độ nước làm mát động cơ đạt 96°C (Ngưỡng cảnh báo: 95°C)',
    occurredAt: '2026-08-26 07:20:00',
    status: 'resolved',
  }
];

export const MOCK_PRODUCTIVITY_REPORTS: ProductivityReportItem[] = [
  {
    id: 'RPT-01',
    plateNumber: '70C-128.45',
    vehicleType: 'Xe kéo rơ-moóc',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    operationalDays: 25,
    totalKm: 3420,
    totalEngineHours: 198.5,
    tripsCount: 48,
    payloadTons: 1080.0,
    fuelConsumedLiters: 1120.0,
    avgLitersPerHour: 5.64,
    efficiencyScore: 96.8,
  },
  {
    id: 'RPT-02',
    plateNumber: '81A-049.21',
    vehicleType: 'Máy cày Kubota',
    klhName: 'Khu liên hợp Koun Mom (Campuchia)',
    operationalDays: 24,
    totalKm: 890,
    totalEngineHours: 215.0,
    tripsCount: 36,
    payloadTons: 0,
    fuelConsumedLiters: 1540.0,
    avgLitersPerHour: 7.16,
    efficiencyScore: 94.2,
  },
  {
    id: 'RPT-03',
    plateNumber: '70C-198.88',
    vehicleType: 'Xe tải ben 15T',
    klhName: 'Khu liên hợp Snoul (Campuchia)',
    operationalDays: 26,
    totalKm: 2850,
    totalEngineHours: 165.0,
    tripsCount: 78,
    payloadTons: 1170.0,
    fuelConsumedLiters: 890.0,
    avgLitersPerHour: 5.39,
    efficiencyScore: 98.1,
  }
];

export const MOCK_MASTER_UNITS: MasterUnit[] = [
  {
    id: 'UNIT-01',
    code: 'KLH-SN',
    name: 'Khu liên hợp Snoul (Campuchia)',
    parentUnit: 'Tập đoàn THACO AGRI',
    unitType: 'KLH',
    headOfficer: 'Nguyễn Tiến Hưng (Giám đốc KLH)',
    contactPhone: '+855 88 111 2222',
    locationAddress: 'Snoul District, Kratie Province, Cambodia',
    vehicleCount: 285,
  },
  {
    id: 'UNIT-02',
    code: 'KLH-KM',
    name: 'Khu liên hợp Koun Mom (Campuchia)',
    parentUnit: 'Tập đoàn THACO AGRI',
    unitType: 'KLH',
    headOfficer: 'Lê Văn Hoàng (Giám đốc KLH)',
    contactPhone: '+855 88 333 4444',
    locationAddress: 'Koun Mom District, Ratanakiri Province, Cambodia',
    vehicleCount: 240,
  },
  {
    id: 'UNIT-03',
    code: 'KLH-IP',
    name: 'Khu liên hợp Ia Puch (Gia Lai)',
    parentUnit: 'Tập đoàn THACO AGRI',
    unitType: 'KLH',
    headOfficer: 'Võ Minh Trí (Giám đốc KLH)',
    contactPhone: '0903 888 777',
    locationAddress: 'Huyện Chư Prông, Tỉnh Gia Lai, Việt Nam',
    vehicleCount: 165,
  }
];

export const MOCK_USERS: SystemUser[] = [
  {
    id: 'USR-01',
    username: 'admin',
    fullName: 'Quản trị viên Hệ thống THACO AGRI',
    email: 'admin.fleet@thacoagri.com.vn',
    role: 'SuperAdmin',
    assignedKLH: 'Toàn bộ Khu liên hợp',
    status: 'active',
    lastLogin: '2026-08-26 07:45:00',
  },
  {
    id: 'USR-02',
    username: 'hung.nguyentien',
    fullName: 'Nguyễn Tiến Hưng',
    email: 'hung.nguyentien@thacoagri.com.vn',
    role: 'GiamDocKLH',
    assignedKLH: 'Khu liên hợp Snoul (Campuchia)',
    status: 'active',
    lastLogin: '2026-08-26 06:30:00',
  },
  {
    id: 'USR-03',
    username: 'manh.tranvan',
    fullName: 'Trần Văn Mạnh',
    email: 'manh.tranvan@thacoagri.com.vn',
    role: 'DieuHanhDoiXe',
    assignedKLH: 'Khu liên hợp Snoul (Campuchia)',
    status: 'active',
    lastLogin: '2026-08-26 07:00:00',
  }
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'AUD-001',
    userFullName: 'Trần Văn Mạnh',
    action: 'DISPATCH',
    module: 'Lệnh điều xe',
    targetEntity: 'LĐX-SN-0826-001',
    ipAddress: '192.168.10.45',
    timestamp: '2026-08-26 05:55:12',
    details: 'Tạo mới và phê duyệt lệnh điều xe container chuối cho xe 70C-128.45',
  },
  {
    id: 'AUD-002',
    userFullName: 'Đỗ Mạnh Cường',
    action: 'CREATE',
    module: 'Nhiên liệu',
    targetEntity: 'NL-SN-2608-0112',
    ipAddress: '192.168.10.88',
    timestamp: '2026-08-26 05:46:30',
    details: 'Cấp phát 220.0 Lít dầu DO 0.05S-II qua cột bơm số 1 cho xe 70C-128.45',
  }
];
