
-- ================= TABLE: companies ================
Table	Create Table
companies	CREATE TABLE `companies` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `name` varchar(191) NOT NULL,\n  `address` varchar(191) NOT NULL,\n  `field` varchar(191) NOT NULL,\n  `businessLicense` varchar(191) NOT NULL,\n  `charterCapital` varchar(191) NOT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `companies_code_key` (`code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: users ================
Table	Create Table
users	CREATE TABLE `users` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `username` varchar(191) NOT NULL,\n  `passwordHash` varchar(191) NOT NULL,\n  `fullName` varchar(191) NOT NULL,\n  `phone` varchar(191) DEFAULT NULL,\n  `role` enum('SUPER_ADMIN','DISPATCHER','FARM_MANAGER','WORKSHOP_MANAGER','FUEL_STOREKEEPER','DRIVER') NOT NULL DEFAULT 'DRIVER',\n  `unit` enum('NT1','NT2','XN_BO','TT_BTSC','BAN_CO_GIOI','TOAN_KLH') NOT NULL DEFAULT 'NT1',\n  `employmentStatus` enum('DANG_LAM_VIEC','DA_NGHI_VIEC') NOT NULL DEFAULT 'DANG_LAM_VIEC',\n  `joinedDate` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `resignedDate` datetime(3) DEFAULT NULL,\n  `resignedReason` text DEFAULT NULL,\n  `licenseClass` enum('BANG_MAY_NONG_NGHIEP','HANG_C','HANG_FC','HANG_B2','HANG_D') DEFAULT 'BANG_MAY_NONG_NGHIEP',\n  `licenseNumber` varchar(191) DEFAULT NULL,\n  `licenseExpiryDate` datetime(3) DEFAULT NULL,\n  `healthCheckExpiryDate` datetime(3) DEFAULT NULL,\n  `currentShiftStatus` enum('DANG_VAN_HANH','SAN_SANG','NGHI_PHEP_CA') DEFAULT 'SAN_SANG',\n  `currentLocation` varchar(191) DEFAULT 'Bãi Xe Trung Tâm',\n  `assignedVehicleId` int(11) DEFAULT NULL,\n  `avatarUrl` text DEFAULT NULL,\n  `isActive` tinyint(1) NOT NULL DEFAULT 1,\n  `notes` text DEFAULT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `users_code_key` (`code`),\n  UNIQUE KEY `users_username_key` (`username`),\n  KEY `users_role_idx` (`role`),\n  KEY `users_unit_idx` (`unit`),\n  KEY `users_employmentStatus_idx` (`employmentStatus`),\n  KEY `users_currentShiftStatus_idx` (`currentShiftStatus`),\n  KEY `users_assignedVehicleId_fkey` (`assignedVehicleId`),\n  CONSTRAINT `users_assignedVehicleId_fkey` FOREIGN KEY (`assignedVehicleId`) REFERENCES `vehicles` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: employees ================
Table	Create Table
employees	CREATE TABLE `employees` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `empCode` varchar(191) NOT NULL,\n  `fullName` varchar(191) NOT NULL,\n  `businessUnit` varchar(191) DEFAULT NULL,\n  `complex` varchar(191) DEFAULT NULL,\n  `enterprise` varchar(191) DEFAULT NULL,\n  `farm` varchar(191) DEFAULT NULL,\n  `team` varchar(191) DEFAULT NULL,\n  `position` varchar(191) DEFAULT NULL,\n  `licenseClass` varchar(191) DEFAULT NULL,\n  `licenseNumber` varchar(191) DEFAULT NULL,\n  `licenseExpiryDate` varchar(191) DEFAULT NULL,\n  `healthCheckExpiryDate` varchar(191) DEFAULT NULL,\n  `status` varchar(191) NOT NULL DEFAULT 'Hoạt động',\n  `username` varchar(191) DEFAULT NULL,\n  `phone` varchar(191) DEFAULT NULL,\n  `email` varchar(191) DEFAULT NULL,\n  `joinedDate` varchar(191) DEFAULT NULL,\n  `idCardNumber` varchar(191) DEFAULT NULL,\n  `idCardIssueDate` varchar(191) DEFAULT NULL,\n  `idCardIssuePlace` varchar(191) DEFAULT NULL,\n  `taxCode` varchar(191) DEFAULT NULL,\n  `bankAccount` varchar(191) DEFAULT NULL,\n  `bankName` varchar(191) DEFAULT NULL,\n  `salaryGrade` varchar(191) DEFAULT NULL,\n  `baseSalary` double DEFAULT NULL,\n  `coefficients` double DEFAULT NULL,\n  `insuranceSalary` double DEFAULT NULL,\n  `allowancesJson` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`allowancesJson`)),\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `employees_empCode_key` (`empCode`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: vehicles ================
Table	Create Table
vehicles	CREATE TABLE `vehicles` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `plate` varchar(191) NOT NULL,\n  `name` varchar(191) NOT NULL,\n  `category` enum('MAY_CAY','MAY_KEO','XE_BEN','XE_BON','XE_XUC','XE_NANG','XE_BAN_TAI','XE_CONTAINER') NOT NULL,\n  `unit` enum('NT1','NT2','XN_BO','TT_BTSC','BAN_CO_GIOI','TOAN_KLH') NOT NULL,\n  `defaultDriverId` int(11) DEFAULT NULL,\n  `secondaryDriverId` int(11) DEFAULT NULL,\n  `status` enum('HOAT_DONG','TAM_DUNG','BAO_DUONG','SUA_CHUA','CHO_PHAN_CONG') NOT NULL DEFAULT 'CHO_PHAN_CONG',\n  `totalMachineHours` double NOT NULL DEFAULT 0,\n  `hoursSinceLastService` double NOT NULL DEFAULT 0,\n  `alertTier` enum('GREEN','AMBER','RED') NOT NULL DEFAULT 'GREEN',\n  `odoKm` double NOT NULL DEFAULT 0,\n  `fuelRateStandard` double NOT NULL DEFAULT 12.5,\n  `currentLat` double DEFAULT 13.5678,\n  `currentLng` double DEFAULT 106.8901,\n  `currentLocationName` varchar(191) DEFAULT 'Nông trường 1 - Lô A03',\n  `lastGpsUpdate` datetime(3) DEFAULT current_timestamp(3),\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `vehicles_code_key` (`code`),\n  UNIQUE KEY `vehicles_plate_key` (`plate`),\n  KEY `vehicles_category_idx` (`category`),\n  KEY `vehicles_unit_idx` (`unit`),\n  KEY `vehicles_status_idx` (`status`),\n  KEY `vehicles_alertTier_idx` (`alertTier`),\n  KEY `vehicles_defaultDriverId_fkey` (`defaultDriverId`),\n  KEY `vehicles_secondaryDriverId_fkey` (`secondaryDriverId`),\n  CONSTRAINT `vehicles_defaultDriverId_fkey` FOREIGN KEY (`defaultDriverId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT `vehicles_secondaryDriverId_fkey` FOREIGN KEY (`secondaryDriverId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: agricultural_implements ================
Table	Create Table
agricultural_implements	CREATE TABLE `agricultural_implements` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `name` varchar(191) NOT NULL,\n  `category` enum('DAN_CAY','DAN_BUA','DAN_XOI','DAN_RAI_PHAN','RO_MOOC','DAN_PHUN_THUOC') NOT NULL,\n  `unit` enum('NT1','NT2','XN_BO','TT_BTSC','BAN_CO_GIOI','TOAN_KLH') NOT NULL,\n  `currentVehicleId` int(11) DEFAULT NULL,\n  `status` enum('ATTACHED','IN_DEPOT','MAINTENANCE') NOT NULL DEFAULT 'IN_DEPOT',\n  `technicalCondition` enum('GOOD','WORN_OUT','NEED_REPAIR') NOT NULL DEFAULT 'GOOD',\n  `standardPurpose` varchar(191) DEFAULT NULL,\n  `attachedAt` datetime(3) DEFAULT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `agricultural_implements_code_key` (`code`),\n  KEY `agricultural_implements_category_idx` (`category`),\n  KEY `agricultural_implements_unit_idx` (`unit`),\n  KEY `agricultural_implements_status_idx` (`status`),\n  KEY `agricultural_implements_currentVehicleId_fkey` (`currentVehicleId`),\n  CONSTRAINT `agricultural_implements_currentVehicleId_fkey` FOREIGN KEY (`currentVehicleId`) REFERENCES `vehicles` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: implement_attachment_logs ================
Table	Create Table
implement_attachment_logs	CREATE TABLE `implement_attachment_logs` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `vehicleId` int(11) NOT NULL,\n  `implementId` int(11) NOT NULL,\n  `actorId` int(11) NOT NULL,\n  `attachedAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `detachedAt` datetime(3) DEFAULT NULL,\n  `startWearMm` double NOT NULL DEFAULT 0,\n  `endWearMm` double DEFAULT NULL,\n  `notes` text DEFAULT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  PRIMARY KEY (`id`),\n  KEY `implement_attachment_logs_vehicleId_idx` (`vehicleId`),\n  KEY `implement_attachment_logs_implementId_idx` (`implementId`),\n  KEY `implement_attachment_logs_actorId_idx` (`actorId`),\n  CONSTRAINT `implement_attachment_logs_actorId_fkey` FOREIGN KEY (`actorId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `implement_attachment_logs_implementId_fkey` FOREIGN KEY (`implementId`) REFERENCES `agricultural_implements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `implement_attachment_logs_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: production_plans ================
Table	Create Table
production_plans	CREATE TABLE `production_plans` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `title` varchar(191) NOT NULL,\n  `stage` enum('LAM_DAT','TRONG_MOI','THU_HOACH') NOT NULL DEFAULT 'LAM_DAT',\n  `unit` enum('NT1','NT2','XN_BO','TT_BTSC','BAN_CO_GIOI','TOAN_KLH') NOT NULL DEFAULT 'NT1',\n  `lotPlot` varchar(191) NOT NULL,\n  `targetAreaHa` double NOT NULL DEFAULT 0,\n  `completedAreaHa` double NOT NULL DEFAULT 0,\n  `assignedVehiclesCount` int(11) NOT NULL DEFAULT 0,\n  `fuelQuotaLiters` double NOT NULL DEFAULT 0,\n  `fuelUsedLiters` double NOT NULL DEFAULT 0,\n  `supervisorId` int(11) DEFAULT NULL,\n  `startDate` datetime(3) NOT NULL,\n  `endDate` datetime(3) NOT NULL,\n  `status` enum('PENDING','IN_PROGRESS','PAUSED','COMPLETED') NOT NULL DEFAULT 'PENDING',\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `production_plans_code_key` (`code`),\n  KEY `production_plans_stage_idx` (`stage`),\n  KEY `production_plans_unit_idx` (`unit`),\n  KEY `production_plans_status_idx` (`status`),\n  KEY `production_plans_supervisorId_fkey` (`supervisorId`),\n  CONSTRAINT `production_plans_supervisorId_fkey` FOREIGN KEY (`supervisorId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: production_plot_progresses ================
Table	Create Table
production_plot_progresses	CREATE TABLE `production_plot_progresses` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `planId` int(11) NOT NULL,\n  `plotName` varchar(191) NOT NULL,\n  `taskName` varchar(191) DEFAULT NULL,\n  `areaHa` double NOT NULL,\n  `status` enum('CHUA_THUC_HIEN','DANG_THUC_HIEN','HOAN_THANH') NOT NULL DEFAULT 'CHUA_THUC_HIEN',\n  `receivedAt` datetime(3) DEFAULT NULL,\n  `completedAt` datetime(3) DEFAULT NULL,\n  `actualMachineHours` double NOT NULL DEFAULT 0,\n  `actualFuelLiters` double NOT NULL DEFAULT 0,\n  `driverId` int(11) DEFAULT NULL,\n  `vehicleId` int(11) DEFAULT NULL,\n  `isSettledFinance` tinyint(1) NOT NULL DEFAULT 0,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `production_plot_progresses_planId_idx` (`planId`),\n  KEY `production_plot_progresses_driverId_idx` (`driverId`),\n  KEY `production_plot_progresses_vehicleId_idx` (`vehicleId`),\n  CONSTRAINT `production_plot_progresses_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT `production_plot_progresses_planId_fkey` FOREIGN KEY (`planId`) REFERENCES `production_plans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `production_plot_progresses_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: production_audit_trails ================
Table	Create Table
production_audit_trails	CREATE TABLE `production_audit_trails` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `planId` int(11) NOT NULL,\n  `actorId` int(11) NOT NULL,\n  `action` varchar(191) NOT NULL,\n  `reason` text NOT NULL,\n  `approvedBy` varchar(191) DEFAULT NULL,\n  `timestamp` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  PRIMARY KEY (`id`),\n  KEY `production_audit_trails_planId_idx` (`planId`),\n  KEY `production_audit_trails_actorId_idx` (`actorId`),\n  CONSTRAINT `production_audit_trails_actorId_fkey` FOREIGN KEY (`actorId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `production_audit_trails_planId_fkey` FOREIGN KEY (`planId`) REFERENCES `production_plans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: dispatch_orders ================
Table	Create Table
dispatch_orders	CREATE TABLE `dispatch_orders` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `requesterId` int(11) NOT NULL,\n  `unit` enum('NT1','NT2','XN_BO','TT_BTSC','BAN_CO_GIOI','TOAN_KLH') NOT NULL,\n  `purpose` varchar(191) NOT NULL,\n  `origin` varchar(191) NOT NULL,\n  `destination` varchar(191) NOT NULL,\n  `vehicleId` int(11) NOT NULL,\n  `driverId` int(11) NOT NULL,\n  `departureTime` datetime(3) NOT NULL,\n  `returnTime` datetime(3) DEFAULT NULL,\n  `status` enum('PENDING','APPROVED','RUNNING','COMPLETED','REJECTED') NOT NULL DEFAULT 'PENDING',\n  `isDelayed` tinyint(1) NOT NULL DEFAULT 0,\n  `notes` text DEFAULT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `dispatch_orders_code_key` (`code`),\n  KEY `dispatch_orders_unit_idx` (`unit`),\n  KEY `dispatch_orders_status_idx` (`status`),\n  KEY `dispatch_orders_vehicleId_idx` (`vehicleId`),\n  KEY `dispatch_orders_driverId_idx` (`driverId`),\n  KEY `dispatch_orders_requesterId_fkey` (`requesterId`),\n  CONSTRAINT `dispatch_orders_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `dispatch_orders_requesterId_fkey` FOREIGN KEY (`requesterId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `dispatch_orders_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: transport_orders ================
Table	Create Table
transport_orders	CREATE TABLE `transport_orders` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `routeType` enum('ONE_WAY','ROUND_TRIP') NOT NULL DEFAULT 'ROUND_TRIP',\n  `cargoType` varchar(191) NOT NULL,\n  `tonnage` double NOT NULL,\n  `origin` varchar(191) NOT NULL,\n  `destination` varchar(191) NOT NULL,\n  `vehicleId` int(11) NOT NULL,\n  `driverId` int(11) NOT NULL,\n  `departureTime` datetime(3) NOT NULL,\n  `arrivalTime` datetime(3) DEFAULT NULL,\n  `speedKmH` double NOT NULL DEFAULT 0,\n  `maxSpeedLimit` double NOT NULL DEFAULT 70,\n  `isRouteDeviated` tinyint(1) NOT NULL DEFAULT 0,\n  `deviationReason` text DEFAULT NULL,\n  `status` enum('PENDING','IN_TRANSIT','DELIVERED','DEVIATED') NOT NULL DEFAULT 'PENDING',\n  `returnCargoName` varchar(191) DEFAULT NULL,\n  `returnTonnage` double DEFAULT 0,\n  `returnDestination` varchar(191) DEFAULT NULL,\n  `returnDriverStatus` enum('EMPTY_DISPATCHED','RETURN_LOADED','RETURN_DELIVERED') NOT NULL DEFAULT 'EMPTY_DISPATCHED',\n  `costSavedVnd` double NOT NULL DEFAULT 0,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `transport_orders_code_key` (`code`),\n  KEY `transport_orders_routeType_idx` (`routeType`),\n  KEY `transport_orders_status_idx` (`status`),\n  KEY `transport_orders_vehicleId_idx` (`vehicleId`),\n  KEY `transport_orders_driverId_idx` (`driverId`),\n  CONSTRAINT `transport_orders_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `transport_orders_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: feed_raw_materials ================
Table	Create Table
feed_raw_materials	CREATE TABLE `feed_raw_materials` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `name` varchar(191) NOT NULL,\n  `groupType` enum('PHU_PHAM_CHUOI','CO_VOI','TMR_VO_BEO','BA_BIA','CAM_VIEN','KHOANG_PREMIX') NOT NULL DEFAULT 'PHU_PHAM_CHUOI',\n  `moisturePercent` double NOT NULL DEFAULT 65,\n  `isCustomAdded` tinyint(1) NOT NULL DEFAULT 0,\n  `createdById` int(11) DEFAULT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `feed_raw_materials_name_key` (`name`),\n  KEY `feed_raw_materials_groupType_idx` (`groupType`),\n  KEY `feed_raw_materials_createdById_fkey` (`createdById`),\n  CONSTRAINT `feed_raw_materials_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: internal_feed_trips ================
Table	Create Table
internal_feed_trips	CREATE TABLE `internal_feed_trips` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `materialId` int(11) NOT NULL,\n  `vehicleId` int(11) NOT NULL,\n  `driverId` int(11) NOT NULL,\n  `sourceLocation` varchar(191) NOT NULL,\n  `transferPoint` varchar(191) DEFAULT NULL,\n  `destinationLocation` varchar(191) NOT NULL,\n  `dispatchWeightTons` double NOT NULL,\n  `receiveWeightTons` double DEFAULT NULL,\n  `weightDiffPercent` double DEFAULT 0,\n  `slaWindowStart` datetime(3) NOT NULL,\n  `slaWindowEnd` datetime(3) NOT NULL,\n  `departureTime` datetime(3) DEFAULT NULL,\n  `completedFeedTime` datetime(3) DEFAULT NULL,\n  `slaStatus` enum('ON_TIME','DELAYED') NOT NULL DEFAULT 'ON_TIME',\n  `delayReason` text DEFAULT NULL,\n  `receiverSignature` text DEFAULT NULL,\n  `isSettled` tinyint(1) NOT NULL DEFAULT 0,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `internal_feed_trips_code_key` (`code`),\n  KEY `internal_feed_trips_materialId_idx` (`materialId`),\n  KEY `internal_feed_trips_vehicleId_idx` (`vehicleId`),\n  KEY `internal_feed_trips_driverId_idx` (`driverId`),\n  KEY `internal_feed_trips_slaStatus_idx` (`slaStatus`),\n  CONSTRAINT `internal_feed_trips_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `internal_feed_trips_materialId_fkey` FOREIGN KEY (`materialId`) REFERENCES `feed_raw_materials` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `internal_feed_trips_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: fuel_warehouses ================
Table	Create Table
fuel_warehouses	CREATE TABLE `fuel_warehouses` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `name` varchar(191) NOT NULL,\n  `type` enum('STATIONARY_TANK_45000L','MOBILE_TRUCK_5000L') NOT NULL DEFAULT 'STATIONARY_TANK_45000L',\n  `capacityLiters` double NOT NULL DEFAULT 45000,\n  `currentStockLiters` double NOT NULL DEFAULT 38500,\n  `unit` enum('NT1','NT2','XN_BO','TT_BTSC','BAN_CO_GIOI','TOAN_KLH') NOT NULL DEFAULT 'BAN_CO_GIOI',\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `fuel_warehouses_type_idx` (`type`),\n  KEY `fuel_warehouses_unit_idx` (`unit`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: fuel_dispense_tickets ================
Table	Create Table
fuel_dispense_tickets	CREATE TABLE `fuel_dispense_tickets` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `ticketCode` varchar(191) NOT NULL,\n  `warehouseId` int(11) NOT NULL,\n  `vehicleId` int(11) NOT NULL,\n  `driverId` int(11) NOT NULL,\n  `dispensedLiters` double NOT NULL,\n  `engineOdoHours` double NOT NULL,\n  `quotaLiters` double NOT NULL,\n  `varianceLiters` double NOT NULL DEFAULT 0,\n  `variancePercent` double NOT NULL DEFAULT 0,\n  `isExcess` tinyint(1) NOT NULL DEFAULT 0,\n  `qrCodePayload` text DEFAULT NULL,\n  `operatorId` int(11) NOT NULL,\n  `dispensedAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `fuel_dispense_tickets_ticketCode_key` (`ticketCode`),\n  KEY `fuel_dispense_tickets_warehouseId_idx` (`warehouseId`),\n  KEY `fuel_dispense_tickets_vehicleId_idx` (`vehicleId`),\n  KEY `fuel_dispense_tickets_driverId_idx` (`driverId`),\n  KEY `fuel_dispense_tickets_operatorId_idx` (`operatorId`),\n  KEY `fuel_dispense_tickets_isExcess_idx` (`isExcess`),\n  CONSTRAINT `fuel_dispense_tickets_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `fuel_dispense_tickets_operatorId_fkey` FOREIGN KEY (`operatorId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `fuel_dispense_tickets_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `fuel_dispense_tickets_warehouseId_fkey` FOREIGN KEY (`warehouseId`) REFERENCES `fuel_warehouses` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: maintenance_records ================
Table	Create Table
maintenance_records	CREATE TABLE `maintenance_records` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `vehicleId` int(11) NOT NULL,\n  `technicianId` int(11) NOT NULL,\n  `currentHours` double NOT NULL,\n  `hoursToNextService` double NOT NULL DEFAULT 250,\n  `alertTier` enum('GREEN','AMBER','RED') NOT NULL DEFAULT 'GREEN',\n  `checklistJson` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`checklistJson`)),\n  `status` enum('SCHEDULED','IN_SERVICE','COMPLETED') NOT NULL DEFAULT 'SCHEDULED',\n  `completedAt` datetime(3) DEFAULT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `maintenance_records_vehicleId_idx` (`vehicleId`),\n  KEY `maintenance_records_technicianId_idx` (`technicianId`),\n  KEY `maintenance_records_status_idx` (`status`),\n  CONSTRAINT `maintenance_records_technicianId_fkey` FOREIGN KEY (`technicianId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `maintenance_records_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: repair_tickets ================
Table	Create Table
repair_tickets	CREATE TABLE `repair_tickets` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `vehicleId` int(11) NOT NULL,\n  `reportedByDriverId` int(11) DEFAULT NULL,\n  `assignedTechnicianId` int(11) DEFAULT NULL,\n  `repairTier` enum('TIEU_TU','TRUNG_TU','DAI_TU','SOS_CUU_HO') NOT NULL DEFAULT 'TIEU_TU',\n  `issueDescription` text NOT NULL,\n  `isGeneratedFromMaintenance` tinyint(1) NOT NULL DEFAULT 0,\n  `maintenanceRecordId` int(11) DEFAULT NULL,\n  `status` enum('RECEIVED','IN_REPAIR','WAITING_PARTS','COMPLETED') NOT NULL DEFAULT 'RECEIVED',\n  `estimatedCostVnd` double NOT NULL DEFAULT 0,\n  `actualCostVnd` double NOT NULL DEFAULT 0,\n  `replacedPartsJson` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`replacedPartsJson`)),\n  `receivedDate` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `completedDate` datetime(3) DEFAULT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `repair_tickets_code_key` (`code`),\n  KEY `repair_tickets_vehicleId_idx` (`vehicleId`),\n  KEY `repair_tickets_repairTier_idx` (`repairTier`),\n  KEY `repair_tickets_status_idx` (`status`),\n  KEY `repair_tickets_reportedByDriverId_fkey` (`reportedByDriverId`),\n  KEY `repair_tickets_assignedTechnicianId_fkey` (`assignedTechnicianId`),\n  KEY `repair_tickets_maintenanceRecordId_fkey` (`maintenanceRecordId`),\n  CONSTRAINT `repair_tickets_assignedTechnicianId_fkey` FOREIGN KEY (`assignedTechnicianId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT `repair_tickets_maintenanceRecordId_fkey` FOREIGN KEY (`maintenanceRecordId`) REFERENCES `maintenance_records` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT `repair_tickets_reportedByDriverId_fkey` FOREIGN KEY (`reportedByDriverId`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT `repair_tickets_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: workshop_owed_part_notes ================
Table	Create Table
workshop_owed_part_notes	CREATE TABLE `workshop_owed_part_notes` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `maintenanceRecordId` int(11) NOT NULL,\n  `vehicleId` int(11) NOT NULL,\n  `missingPartName` varchar(191) NOT NULL,\n  `partCode` varchar(191) DEFAULT NULL,\n  `scheduledRestockDate` datetime(3) DEFAULT NULL,\n  `isResolved` tinyint(1) NOT NULL DEFAULT 0,\n  `resolvedAt` datetime(3) DEFAULT NULL,\n  `technicianNotes` text DEFAULT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `workshop_owed_part_notes_maintenanceRecordId_idx` (`maintenanceRecordId`),\n  KEY `workshop_owed_part_notes_vehicleId_idx` (`vehicleId`),\n  KEY `workshop_owed_part_notes_isResolved_idx` (`isResolved`),\n  CONSTRAINT `workshop_owed_part_notes_maintenanceRecordId_fkey` FOREIGN KEY (`maintenanceRecordId`) REFERENCES `maintenance_records` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `workshop_owed_part_notes_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: driver_kpis ================
Table	Create Table
driver_kpis	CREATE TABLE `driver_kpis` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `driverId` int(11) NOT NULL,\n  `monthYear` varchar(191) NOT NULL,\n  `tripsCount` int(11) NOT NULL DEFAULT 0,\n  `tripsScore` double NOT NULL DEFAULT 25,\n  `distanceKm` double NOT NULL DEFAULT 0,\n  `distanceScore` double NOT NULL DEFAULT 25,\n  `machineHours` double NOT NULL DEFAULT 0,\n  `hoursScore` double NOT NULL DEFAULT 25,\n  `fuelSavedLiters` double NOT NULL DEFAULT 0,\n  `fuelScore` double NOT NULL DEFAULT 25,\n  `totalScore` double NOT NULL DEFAULT 100,\n  `rankGrade` enum('HANG_A','HANG_B','HANG_C','HANG_D') NOT NULL DEFAULT 'HANG_A',\n  `bonusAmountVnd` double NOT NULL DEFAULT 1500000,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `driver_kpis_driverId_monthYear_key` (`driverId`,`monthYear`),\n  KEY `driver_kpis_driverId_idx` (`driverId`),\n  KEY `driver_kpis_rankGrade_idx` (`rankGrade`),\n  CONSTRAINT `driver_kpis_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: driver_sos_alerts ================
Table	Create Table
driver_sos_alerts	CREATE TABLE `driver_sos_alerts` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `driverId` int(11) NOT NULL,\n  `vehicleId` int(11) NOT NULL,\n  `lat` double NOT NULL,\n  `lng` double NOT NULL,\n  `lotLocation` varchar(191) NOT NULL,\n  `emergencyType` enum('HONG_MAY','THUNG_LOP','SA_LAY_RUONG','TAI_NAN','HET_DAU_DOT_XUAT') NOT NULL DEFAULT 'HONG_MAY',\n  `photoUrl` text DEFAULT NULL,\n  `description` text NOT NULL,\n  `status` enum('PENDING','DISPATCHED','RESOLVED') NOT NULL DEFAULT 'PENDING',\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `driver_sos_alerts_driverId_idx` (`driverId`),\n  KEY `driver_sos_alerts_vehicleId_idx` (`vehicleId`),\n  KEY `driver_sos_alerts_status_idx` (`status`),\n  CONSTRAINT `driver_sos_alerts_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n  CONSTRAINT `driver_sos_alerts_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: catalogs ================
Table	Create Table
catalogs	CREATE TABLE `catalogs` (\n  `id` varchar(191) NOT NULL,\n  `code` varchar(191) NOT NULL,\n  `name` varchar(191) NOT NULL,\n  `type` enum('COMPLEX','DEPARTMENT','ENTERPRISE','FARM','TEAM','PLOT','LAND_PARCEL') NOT NULL,\n  `parentCode` varchar(191) DEFAULT NULL,\n  `parentName` varchar(191) DEFAULT NULL,\n  `enterpriseName` varchar(191) DEFAULT NULL,\n  `farmName` varchar(191) DEFAULT NULL,\n  `plotStatus` varchar(191) DEFAULT NULL,\n  `systemId` varchar(191) DEFAULT NULL,\n  `address` varchar(191) DEFAULT NULL,\n  `managerName` varchar(191) DEFAULT NULL,\n  `phone` varchar(191) DEFAULT NULL,\n  `areaHa` double DEFAULT NULL,\n  `status` varchar(191) NOT NULL DEFAULT 'HOAT_DONG',\n  `description` text DEFAULT NULL,\n  `createdUser` varchar(191) DEFAULT 'admin',\n  `createdDate` varchar(191) DEFAULT NULL,\n  `updatedUser` varchar(191) DEFAULT 'admin',\n  `updatedDate` varchar(191) DEFAULT NULL,\n  `confirmedUser` varchar(191) DEFAULT NULL,\n  `confirmedDate` varchar(191) DEFAULT NULL,\n  `deletedUser` varchar(191) DEFAULT NULL,\n  `deletedDate` varchar(191) DEFAULT NULL,\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `catalogs_type_idx` (`type`),\n  KEY `catalogs_code_idx` (`code`),\n  KEY `catalogs_parentCode_idx` (`parentCode`),\n  KEY `catalogs_status_idx` (`status`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- ================= TABLE: personnel_partners ================
Table	Create Table
personnel_partners	CREATE TABLE `personnel_partners` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `code` varchar(191) NOT NULL,\n  `name` varchar(191) NOT NULL,\n  `complex` varchar(191) DEFAULT NULL,\n  `enterprise` varchar(191) DEFAULT NULL,\n  `farm` varchar(191) DEFAULT NULL,\n  `team` varchar(191) DEFAULT NULL,\n  `position` varchar(191) DEFAULT NULL,\n  `status` varchar(191) NOT NULL DEFAULT 'Hoạt động',\n  `creator` varchar(191) DEFAULT 'admin',\n  `createdAt` datetime(3) NOT NULL DEFAULT current_timestamp(3),\n  `updater` varchar(191) DEFAULT 'admin',\n  `updatedAt` datetime(3) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `personnel_partners_code_key` (`code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

