ALTER TABLE `catalogs`
  MODIFY COLUMN `type` ENUM(
    'COMPLEX','REGION','DEPARTMENT','ENTERPRISE','FARM','TEAM','PLOT','LAND_PARCEL',
    'VEHICLE_CATEGORY','JOB_TYPE','POSITION','JOB_ITEM','ORDER_TYPE','ROUTE',
    'CONSTRUCTION_SITE','SPARE_PART','TECHNICAL_QUOTA','CG_MANAGER','VEHICLE_ORIGIN',
    'PURCHASE_CONDITION','SUPPLIER','COMPANY_OWNER'
  ) NOT NULL,
  ADD COLUMN `normalizedKey` VARCHAR(191) NULL;

CREATE UNIQUE INDEX `catalogs_type_normalizedKey_key` ON `catalogs`(`type`, `normalizedKey`);
