export const DISPATCH_FIRST_DELAY_MINUTES = 15;
export const DISPATCH_REOPEN_AFTER_FIRST_DELAY_MINUTES = 30;
export const DISPATCH_REOPEN_TOTAL_MINUTES =
  DISPATCH_FIRST_DELAY_MINUTES + DISPATCH_REOPEN_AFTER_FIRST_DELAY_MINUTES;

export const DISPATCH_DELAY_SCAN_INTERVAL_MS = 60_000;
